#!/bin/bash
############################################################################
# 
# Module: gateway_status.sh
#
# Function:
#     gateway status will send mail when the Message recived in related Mqqts Topic   
#
# Copyright and License:
#     This file copyright (c) 2022 by
#
#         MCCI Corporation
#         3520 Krums Corners Road
#         Ithaca, NY  14850
#
#     See accompanying LICENSE file for copyright and license information.
#
# Author:
#     Shashi, MCCI   Dec 2022
#
############################################################################*/

while true; do
  mosquitto_sub -C 1 -h training.mcci.io -t test -p 8883 -u shashi -P shashi --capath /etc/ssl/certs/ > temp.txt
  mv temp.txt newtest.txt
  echo "Hello" > shashi.txt
  echo "" >> shashi.txt
  echo "Please Find The Following Gateway Status :" >> shashi.txt
  echo "" >> shashi.txt
  echo "" >> shashi.txt
  awk -F, 'NF > 1 { $1 = $2 } { print $1 }' newtest.txt >> shashi.txt
  awk -F, 'NF > 1 { $1 = $3 } { print $1 }' newtest.txt >> shashi.txt
  awk '/..latitude../{print substr($0, index($0,"latitude") - 0, 25);}' newtest.txt >> shashi.txt
  awk '/..longitude../{print substr($0, index($0,"longitude") - 0, 25);}' newtest.txt >> shashi.txt
  awk '/..last communication../{print substr($0, index($0,"last communication") - 0, 40);}' newtest.txt >> shashi.txt
  echo "" >> shashi.txt
  echo "" >> shashi.txt
  echo "" >> shashi.txt
  echo "" >> shashi.txt
  echo "Please do not reply to this e-mail, as this mail was generated by mqtts_Notify.sh running on iotdashboard.mcci.io" >> shashi.txt
  < shashi.txt mail -s "MQTTS MAIL STATUS" -a From:Admin\<status@iotdashboard.mcci.io\> shashi@mcci.com
done