#!/bin/bash
############################################################################
# 
# Module: gateway_status.sh
#
# Function:
#     gateway status will send mail when the Message recived in related Mqqts Topic   
#
#
# Author:
#     Shashi, MCCI   Dec 2022
#
############################################################################*/

while true; do
  mosquitto_sub -C 1 -h dashboard.example.com -t topic -p 8883 -u user -P userpass --capath /etc/ssl/certs/ > temp.txt
  mv temp.txt newtest.txt
  echo "Hello" > mail.txt
  echo "" >> mail.txt
  echo "Please Find The Following Gateway Status :" >> mail.txt
  echo "" >> mail.txt
  echo "" >> mail.txt
  awk -F, 'NF > 1 { $1 = $2 } { print $1 }' newtest.txt >> mail.txt
  awk -F, 'NF > 1 { $1 = $3 } { print $1 }' newtest.txt >> mail.txt
  awk '/..latitude../{print substr($0, index($0,"latitude") - 0, 25);}' newtest.txt >> mail.txt
  awk '/..longitude../{print substr($0, index($0,"longitude") - 0, 25);}' newtest.txt >> mail.txt
  awk '/..last communication../{print substr($0, index($0,"last communication") - 0, 40);}' newtest.txt >> mail.txt
  echo "" >> mail.txt
  echo "" >> mail.txt
  echo "" >> mail.txt
  echo "" >> mail.txt
  echo "Please do not reply to this e-mail, as this mail was generated by mqtts_Notify.sh running on dashboard.example.com" >> mail.txt
  < mail.txt mail -s "MQTTS MAIL STATUS" -a From:Admin\<status@dashboard.example.com\> user@example.com
done